import {Component} from '@angular/core';
import {FormBuilder, FormControl, FormGroup, Validators} from '@angular/forms';
import {HttpClient} from '@angular/common/http';
import { UserdetailsService } from '../userdetails.service';
import { Router } from '@angular/router';


@Component({
    selector: 'app-registration-form',
    templateUrl:'./registration-form.component.html',
    styleUrls:['registration-form.component.css'],
    
})

export class RegistrationFormComponent{
    value:any;
    r:string[]=[]
    selectedRole:string=''
    empskillids:any[]=[]
    showDropdownMenu = false;
    skills: any[] = [];
    selectedSkills:any[]=[]
    locations:string[]=[
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal"
  ];
    colleges:{[key:string]:string[]}={
        'Tamil Nadu':["Indian Institute of Technology Madras (IIT Madras)",
        "National Institute of Technology Tiruchirappalli (NIT Trichy)",
        "Anna University, Chennai",
        "Vellore Institute of Technology (VIT), Vellore",
        "Madras Institute of Technology, Chennai",
        "College of Engineering, Guindy",
        "PSG College of Technology, Coimbatore",
        "Sri Sivasubramaniya Nadar College of Engineering (SSNCE), Chennai",
        "Thiagarajar College of Engineering, Madurai",
        "Coimbatore Institute of Technology (CIT), Coimbatore",
        "Government College of Technology, Coimbatore",
        "SASTRA University, Thanjavur",
        "SRM Institute of Science and Technology, Chennai",
        "Government College of Engineering, Salem",
        "B.S. Abdur Rahman Crescent Institute of Science and Technology, Chennai",
        "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology, Chennai",
        "Sathyabama Institute of Science and Technology, Chennai",
        "Kumaraguru College of Technology, Coimbatore",
        "St. Joseph's College of Engineering, Chennai",
        "Mepco Schlenk Engineering College, Sivakasi",
        "Rajalakshmi Engineering College, Chennai",
        "Panimalar Engineering College, Chennai",
        "R.M.K. Engineering College, Chennai",
        "Jerusalem College of Engineering, Chennai",
        "Sri Venkateswara College of Engineering, Sriperumbudur",
        "Hindustan Institute of Technology and Science, Chennai",
        "Easwari Engineering College, Chennai",
        "KCG College of Technology, Chennai",
        "Saveetha Engineering College, Chennai",
        "Adhiyamaan College of Engineering, Hosur",
        "Velammal Engineering College, Chennai",
        "Jeppiaar Engineering College, Chennai",
        "Valliammai Engineering College, Kancheepuram",
        "R.M.D. Engineering College, Chennai",
        "Sri Krishna College of Engineering and Technology, Coimbatore",
        "M.Kumarasamy College of Engineering, Karur",
        "PSNA College of Engineering and Technology, Dindigul",
        "Bannari Amman Institute of Technology, Erode",
        "Kamaraj College of Engineering and Technology, Virudhunagar",
        "Government College of Engineering, Tirunelveli",
        "Sri Sai Ram Engineering College, Chennai",
        "Vel Tech Multi Tech Dr. Rangarajan Dr. Sakunthala Engineering College, Chennai",
        "Sri Ramakrishna Engineering College, Coimbatore",
        "Sri Krishna College of Technology, Coimbatore",
        "Sri Ramakrishna Institute of Technology, Coimbatore",
        "Kongu Engineering College, Erode",
        "Government College of Engineering, Bargur",
        "Government College of Engineering, Bodinayakanur",
        "Government College of Engineering, Dharmapuri",
        "Government College of Engineering, Thanjavur","Chennai Institute of Technology, Chennai","Other"],
        'Andhra Pradesh':["Andhra University College of Engineering, Visakhapatnam",
        "Sri Venkateswara University College of Engineering, Tirupati",
        "Jawaharlal Nehru Technological University College of Engineering, Kakinada",
        "Sri Venkateswara College of Engineering, Tirupati",
        "Gayatri Vidya Parishad College of Engineering, Visakhapatnam",
        "GMR Institute of Technology, Rajam",
        "Sagi Ramakrishnam Raju Engineering College, Bhimavaram",
        "Vignan's Foundation for Science, Technology & Research, Guntur",
        "RVR & JC College of Engineering, Guntur",
        "Sri Venkateswara Engineering College, Tirupati",
        "Sree Vidyanikethan Engineering College, Tirupati",
        "Andhra Loyola Institute of Engineering and Technology, Vijayawada",
        "Vasireddy Venkatadri Institute of Technology, Guntur",
        "Vignan's Institute of Information Technology, Visakhapatnam",
        "Anil Neerukonda Institute of Technology and Sciences, Visakhapatnam",
        "G Pulla Reddy Engineering College, Kurnool",
        "Narasaraopeta Engineering College, Narasaraopet",
        "Sri Mittapalli College of Engineering, Guntur",
        "Sri Vasavi Institute of Engineering and Technology, Nandamuru",
        "Rajeev Gandhi Memorial College of Engineering and Technology, Nandyal",
        "Vikas College of Engineering & Technology, Nunna",
        "Vijaya Institute of Technology for Women, Vijayawada",
        "Prasad V Potluri Siddhartha Institute of Technology, Vijayawada",
        "Andhra Pradesh MedTech Zone (AMTZ), Visakhapatnam",
        "Mallareddy College of Engineering and Technology, Secunderabad",
        "Sri Venkateswara Engineering College, Chittoor",
        "Dadi Institute of Engineering and Technology, Vishakapatnam",
        "Kakinada Institute of Engineering & Technology, Kakinada",
        "Madanapalle Institute of Technology and Science, Madanapalle","Other"],
        "Karnataka":["Indian Institute of Science (IISc), Bangalore",
        "International Institute of Information Technology (IIIT), Bangalore",
        "National Institute of Technology Karnataka (NITK), Surathkal",
        "Manipal Institute of Technology, Manipal",
        "R.V. College of Engineering (RVCE), Bangalore",
        "BMS College of Engineering, Bangalore",
        "PES University, Bangalore",
        "MS Ramaiah Institute of Technology (MSRIT), Bangalore",
        "Siddaganga Institute of Technology, Tumkur",
        "JSS Science and Technology University, Mysuru",
        "Dayananda Sagar College of Engineering, Bangalore",
        "Nitte Meenakshi Institute of Technology, Bangalore",
        "Sri Jayachamarajendra College of Engineering (SJCE), Mysuru",
        "Bangalore Institute of Technology (BIT), Bangalore",
        "University Visvesvaraya College of Engineering (UVCE), Bangalore",
        "BMS Institute of Technology and Management, Bangalore",
        "Sri Sairam College of Engineering, Bengaluru",
        "Sir M. Visvesvaraya Institute of Technology (MVIT), Bangalore",
        "Ramaiah Institute of Technology (RIT), Bangalore",
        "New Horizon College of Engineering, Bangalore",
        "KLE Technological University, Hubli",
        "SJB Institute of Technology, Bangalore",
        "Vidya Vardhaka College of Engineering, Mysuru",
        "The National Institute of Engineering (NIE), Mysuru",
        "Reva University, Bangalore",
        "CMR Institute of Technology, Bangalore",
        "BMS School of Architecture, Bangalore",
        "Acharya Institute of Technology, Bangalore",
        "Gogte Institute of Technology, Belagavi",
        "Shri Dharmasthala Manjunatheshwara College of Engineering and Technology, Dharwad","Other"],
        "Assam":["Indian Institute of Technology Guwahati (IIT Guwahati)",
        "National Institute of Technology Silchar (NIT Silchar)",
        "Assam Engineering College, Guwahati",
        "Jorhat Engineering College, Jorhat",
        "Dibrugarh University Institute of Engineering and Technology, Dibrugarh",
        "Gauhati University Institute of Science and Technology, Guwahati",
        "Tezpur University, Tezpur",
        "Assam Don Bosco University, Guwahati",
        "Cotton University, Guwahati",
        "National Law University and Judicial Academy, Guwahati","Other"],
        "Bihar":[ "Indian Institute of Technology Patna (IIT Patna)",
        "National Institute of Technology Patna (NIT Patna)",
        "Birla Institute of Technology, Patna",
        "National Institute of Fashion Technology, Patna",
        "Patna Science College, Patna University",
        "Maulana Azad College, Patna University",
        "Patna Women's College, Patna University",
        "Magadh Mahila College, Patna University",
        "Nalanda College, Biharsharif",
        "B. N. College, Patna University","Other"],
        "Chhattisgarh":["National Institute of Technology, Raipur",
        "Indian Institute of Management, Raipur",
        "Pt. Ravishankar Shukla University, Raipur",
        "Hidayatullah National Law University, Raipur",
        "Government Engineering College, Raipur",
        "Government Engineering College, Bilaspur",
        "National Institute of Technology, Raipur",
        "Chhattisgarh Swami Vivekanand Technical University, Bhilai",
        "Guru Ghasidas Vishwavidyalaya, Bilaspur",
        "Laxmi Narain College of Technology, Bilaspur",
        "Raipur Institute of Technology, Raipur",
        "Bhilai Institute of Technology, Durg",
        "Rungta College of Engineering and Technology, Bhilai","Other"],
        "Goa":[ "Goa Engineering College, Farmagudi",
        "Padre Conceicao College of Engineering, Verna",
        "Shree Rayeshwar Institute of Engineering and Information Technology, Shiroda",
        "Agnel Institute of Technology and Design, Assagao",
        "Don Bosco College of Engineering, Fatorda",
        "Goa College of Engineering, Farmagudi",
        "Padre Conceicao College of Engineering, Verna",
        "Agnel Polytechnic, Verna",
        "Agnel Institute of Technology and Design, Assagao",
        "Institute of Shipbuilding Technology, Vasco da Gama","Other"],
        "Gujarat":[ "Indian Institute of Technology Gandhinagar (IIT Gandhinagar)",
        "Sardar Vallabhbhai National Institute of Technology (SVNIT), Surat",
        "Dhirubhai Ambani Institute of Information and Communication Technology (DAIICT), Gandhinagar",
        "Nirma University, Ahmedabad",
        "Pandit Deendayal Petroleum University (PDPU), Gandhinagar",
        "Institute of Infrastructure Technology Research and Management (IITRAM), Ahmedabad",
        "Vishwakarma Government Engineering College, Ahmedabad",
        "L.D. College of Engineering, Ahmedabad",
        "Gujarat Technological University (GTU), Ahmedabad",
        "Charotar University of Science and Technology (CHARUSAT), Changa","Other"],
        "Kerala":[ "Indian Institute of Technology Palakkad (IIT Palakkad)",
        "National Institute of Technology Calicut (NIT Calicut)",
        "College of Engineering Trivandrum (CET), Trivandrum",
        "Government Engineering College, Thrissur",
        "Government Engineering College, Kozhikode",
        "Government Engineering College, Barton Hill, Trivandrum",
        "Rajiv Gandhi Institute of Technology (RIT), Kottayam",
        "Model Engineering College (MEC), Thrikkakara",
        "TKM College of Engineering, Kollam",
        "Government Engineering College, Kannur",
        "Government Engineering College, Sreekrishnapuram",
        "Federal Institute of Science and Technology (FISAT), Angamaly",
        "Government Model Engineering College, Thrikkakara",
        "MES College of Engineering, Kuttippuram",
        "SCMS School of Engineering and Technology, Ernakulam",
        "College of Engineering, Adoor",
        "LBS Institute of Technology for Women, Thiruvananthapuram",
        "Government Engineering College, Idukki","Other"],
        "Maharashtra":["Indian Institute of Technology Bombay (IIT Bombay)",
        "Visvesvaraya National Institute of Technology (VNIT), Nagpur",
        "College of Engineering Pune (COEP), Pune",
        "Veermata Jijabai Technological Institute (VJTI), Mumbai",
        "Government College of Engineering, Aurangabad",
        "Walchand College of Engineering, Sangli",
        "Sardar Patel College of Engineering (SPCE), Mumbai",
        "Dr. Babasaheb Ambedkar Technological University, Lonere",
        "Government College of Engineering, Amravati",
        "Government College of Engineering, Nagpur",
        "Shri Ramdeobaba College of Engineering and Management, Nagpur",
        "Fr. Conceicao Rodrigues College of Engineering (CRCE), Mumbai",
        "Vishwakarma Institute of Technology (VIT), Pune",
        "Thadomal Shahani Engineering College (TSEC), Mumbai",
        "K.J. Somaiya College of Engineering (KJSCE), Mumbai",
        "Pune Institute of Computer Technology (PICT), Pune",
        "Dwarkadas J. Sanghvi College of Engineering (DJ Sanghvi), Mumbai",
        "Sardar Patel Institute of Technology (SPIT), Mumbai",
        "Vidyalankar Institute of Technology (VIT), Mumbai",
        "Rajarambapu Institute of Technology (RIT), Sangli",
        "Maharashtra Institute of Technology (MIT), Pune",
        "Datta Meghe College of Engineering, Navi Mumbai",
        "Army Institute of Technology (AIT), Pune",
        "Cummins College of Engineering for Women, Pune",
        "Walchand Institute of Technology (WIT), Solapur",
        "Bharati Vidyapeeth Deemed University College of Engineering, Pune",
        "Pillai College of Engineering, Panvel",
        "Indira College of Engineering and Management, Pune",
        "Karmaveer Bhaurao Patil College of Engineering, Satara",
        "Shivaji University, Kolhapur",
        "Vishwakarma Institute of Information Technology (VIIT), Pune",
        "Sinhgad College of Engineering, Pune",
        "Dhole Patil College of Engineering, Pune",
        "Bharati Vidyapeeth College of Engineering, Navi Mumbai",
        "Pimpri Chinchwad College of Engineering (PCCOE), Pune",
        "Yeshwantrao Chavan College of Engineering (YCCE), Nagpur",
        "Kavikulguru Institute of Technology and Science (KITS), Nagpur",
        "Terna Engineering College, Navi Mumbai",
        "Vivekanand Education Society's Institute of Technology (VESIT), Mumbai",
        "Lokmanya Tilak College of Engineering (LTCE), Mumbai",
        "Amity University Mumbai, Mumbai","Other"],
        "Haryana":["National Institute of Technology Kurukshetra (NIT Kurukshetra)",
        "YMCA University of Science and Technology, Faridabad",
        "Deenbandhu Chhotu Ram University of Science and Technology, Murthal",
        "Maharishi Markandeshwar University, Mullana",
        "Guru Jambheshwar University of Science and Technology, Hisar",
        "University Institute of Engineering and Technology, Maharshi Dayanand University, Rohtak",
        "Manav Rachna International Institute of Research and Studies, Faridabad",
        "Dronacharya College of Engineering, Gurgaon",
        "Ambala College of Engineering and Applied Research, Ambala",
        "Vaish College of Engineering, Rohtak",
        "Seth Jai Parkash Mukand Lal Institute of Engineering and Technology, Yamuna Nagar",
        "Guru Nanak Dev Engineering College, Karnal",
        "Bhagwan Mahavir Institute of Engineering and Technology, Sonipat",
        "Panipat Institute of Engineering and Technology, Panipat",
        "Echelon Institute of Technology, Faridabad",
        "Al-Falah School of Engineering and Technology, Faridabad",
        "World College of Technology and Management, Gurgaon",
        "Apeejay Stya University, Gurgaon",
        "Shri Ram College of Engineering and Management, Palwal",
        "NC College of Engineering, Israna",
        "Somany Institute of Technology and Management, Rewari",
        "Seth Jai Parkash Polytechnic, Damla",
        "Swami Devi Dyal Institute of Engineering and Technology, Panchkula",
        "Doon Valley Institute of Engineering and Technology, Karnal","Other"],
        "Himachal Pradesh":["National Institute of Technology Hamirpur (NIT Hamirpur)",
        "Jaypee University of Information Technology, Waknaghat",
        "Indian Institute of Technology Mandi (IIT Mandi)",
        "Himachal Pradesh Technical University, Hamirpur",
        "Green Hills Engineering College, Kumarhatti",
        "Baddi University of Emerging Sciences and Technologies, Baddi",
        "Atal Bihari Vajpayee Government Institute of Engineering and Technology, Pragatinagar",
        "Shiva Institute of Engineering and Technology, Bilaspur",
        "L.R. Institute of Engineering and Technology, Solan",
        "T. R. Abhilashi Memorial Institute of Engineering and Technology, Mandi",
        "Government Polytechnic College, Hamirpur",
        "Sai Ram Educational Trust Group of Institutions, Kangra",
        "Dev Bhoomi Institute of Engineering and Technology, Una",
        "K.C. Group of Research and Professional Institutes, Pandoga",
        "Himachal Institute of Engineering and Technology, Shahpur",
        "L.R. Institute of Legal Studies, Solan","Other"],
        "Jharkhand":["National Institute of Technology Jamshedpur (NIT Jamshedpur)",
        "Birla Institute of Technology, Mesra (BIT Mesra), Ranchi",
        "Government Engineering College, Dumka",
        "R.V.S. College of Engineering & Technology, Jamshedpur",
        "B.A. College of Engineering & Technology, Ghutia, Jamshedpur",
        "Cambridge Institute of Technology, Ranchi",
        "D.A.V. Institute of Engineering & Technology, Daltonganj",
        "K.K. College of Engineering & Management, Dhanbad",
        "Maryland Institute of Technology & Management, Ranchi",
        "Ram Govind Institute of Technology, Koderma",
        "R.T.C. Institute of Technology, Ranchi",
        "Dumka Engineering College, Dumka",
        "Nilai Educational Trust's Group of Institutions, Ranchi",
        "R.V.S. College of Engineering & Technology, Jamshedpur",
        "Usha Martin University, Ranchi","Other"],
        "Madhya Pradesh":[ "Indian Institute of Technology Indore (IIT Indore)",
        "Indian Institute of Technology (Indian School of Mines), Bhopal (IIT Bhopal)",
        "National Institute of Technology Bhopal (NIT Bhopal)",
        "MANIT Bhopal",
        "Shri Govindram Seksaria Institute of Technology and Science (SGSITS), Indore",
        "Jabalpur Engineering College (JEC), Jabalpur",
        "Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV), Bhopal",
        "UIT RGPV, Bhopal",
        "Medi-Caps University, Indore",
        "Ujjain Engineering College, Ujjain",
        "Sagar Institute of Science and Technology (SISTec), Bhopal",
        "Lakshmi Narain College of Technology (LNCT), Bhopal",
        "Technocrats Institute of Technology (TIT), Bhopal",
        "Patel College of Science and Technology (PCST), Indore","Other"],
        "Manipur":[ "National Institute of Technology Manipur (NIT Manipur), Imphal",
        "Manipur Institute of Technology (MIT), Imphal",
        "Imphal Engineering College (IEC), Imphal",
        "Don Bosco College of Engineering and Technology (DBCET), Imphal","Other"],
        "Meghalaya":["National Institute of Technology Meghalaya (NIT Meghalaya), Shillong",
        "University of Science and Technology, Meghalaya (USTM), Ri-Bhoi",
        "Shillong Engineering and Management College (SEMC), Shillong",
        "Techno Global University (TGU), Shillong",
        "Institute of Science and Technology (IST), Meghalaya",
        "Don Bosco College of Engineering and Technology, Shillong","Other"],
        "Mizoram":[ "National Institute of Technology Mizoram (NIT Mizoram), Aizawl",
        "Mizoram University, Aizawl",
        "Government Polytechnic, Aizawl",
        "Lunglei Government College, Lunglei","Other"],
        "Nagaland":[ "National Institute of Technology Nagaland (NIT Nagaland), Dimapur",
        "The Global Open University, Dimapur",
        "Institute of Communication and Information Technology (ICIT), Dimapur",
        "St. Joseph's College, Jakhama",
        "Kohima Science College, Kohima","Other"],
        "Odisha":["National Institute of Technology Rourkela (NIT Rourkela)",
        "Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar)",
        "Veermata Jijabai Technological Institute (VJTI), Mumbai",
        "International Institute of Information Technology (IIIT), Bhubaneswar",
        "Siksha 'O' Anusandhan (SOA) University, Bhubaneswar",
        "College of Engineering and Technology (CET), Bhubaneswar",
        "Indira Gandhi Institute of Technology (IGIT), Sarang",
        "Silicon Institute of Technology (SIT), Bhubaneswar",
        "Gandhi Institute for Technological Advancement (GITA), Bhubaneswar",
        "National Institute of Science and Technology (NIST), Berhampur",
        "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar","Other"],
        "Punjab":["Indian Institute of Technology Ropar (IIT Ropar)",
        "Thapar Institute of Engineering and Technology, Patiala",
        "Punjab Engineering College (PEC), Chandigarh",
        "Dr. B.R. Ambedkar National Institute of Technology Jalandhar (NIT Jalandhar)",
        "Guru Nanak Dev Engineering College, Ludhiana",
        "Sant Longowal Institute of Engineering and Technology (SLIET), Sangrur",
        "Chandigarh University, Chandigarh",
        "Lovely Professional University (LPU), Jalandhar",
        "DAV Institute of Engineering and Technology, Jalandhar",
        "Beant College of Engineering and Technology, Gurdaspur",
        "Guru Nanak Dev University Regional Campus, Gurdaspur","Other"],
        "Rajasthan":["Indian Institute of Technology Jodhpur (IIT Jodhpur)",
        "Malaviya National Institute of Technology Jaipur (MNIT Jaipur)",
        "BITS Pilani, Pilani Campus",
        "Manipal University, Jaipur",
        "Rajasthan Technical University (RTU), Kota",
        "JECRC University, Jaipur",
        "Poornima University, Jaipur",
        "Vivekananda Global University, Jaipur",
        "Jaipur Engineering College and Research Centre (JECRC), Jaipur",
        "Banasthali Vidyapith, Tonk",
        "Rajasthan Institute of Engineering and Technology (RIET), Jaipur",
        "Mody University, Sikar","Other"],
        "Telangana":[ "Indian Institute of Technology Hyderabad (IIT Hyderabad)",
        "International Institute of Information Technology Hyderabad (IIIT Hyderabad)",
        "National Institute of Technology Warangal (NIT Warangal)",
        "BITS Pilani, Hyderabad Campus",
        "Osmania University College of Engineering (OUCE), Hyderabad",
        "Jawaharlal Nehru Technological University Hyderabad (JNTUH), Hyderabad",
        "Vasavi College of Engineering (VCE), Hyderabad",
        "Chaitanya Bharathi Institute of Technology (CBIT), Hyderabad",
        "MVSR Engineering College, Hyderabad",
        "Gokaraju Rangaraju Institute of Engineering and Technology (GRIET), Hyderabad",
        "Sreenidhi Institute of Science and Technology (SNIST), Hyderabad","Other"],
        "Sikkim":["National Institute of Technology Sikkim (NIT Sikkim), Ravangla",
        "Sikkim Manipal Institute of Technology (SMIT), Majitar",
        "Eastern Institute for Integrated Learning in Management University (EIILM), Jorethang",
        "Sikkim University, Gangtok",
        "Namgyal Institute of Technology (NIT), South Sikkim",
        "College of Agricultural Engineering and Post Harvest Technology, Gangtok",
        "Sikkim Government College of Engineering (SGCE), Sikkim",
        "Sikkim Institute of Science and Technology (SIST), East Sikkim",
        "Sikkim Institute of Advanced Technological Education (SIT), Gangtok",
        "Advanced Institute of Technology and Management (AITM), East Sikkim","Other"],
         "Tripura":[ "National Institute of Technology Agartala (NIT Agartala)",
         "Tripura Institute of Technology (TIT), Narsingarh",
         "Techno India Agartala (TIA), Jirania",
         "Institute of Science and Technology, Agartala",
         "Government Degree College, Dharmanagar",
         "Rahul Foundation, Agartala",
         "Global Polytechnic College, Agartala","Other"],
         "Uttar Pradesh":[ "Indian Institute of Technology Kanpur (IIT Kanpur)",
         "Indian Institute of Technology (BHU) Varanasi",
         "Motilal Nehru National Institute of Technology (MNNIT), Allahabad",
         "Institute of Engineering and Technology (IET), Lucknow",
         "Harcourt Butler Technical University (HBTU), Kanpur",
         "Madan Mohan Malaviya University of Technology (MMMUT), Gorakhpur",
         "Ajay Kumar Garg Engineering College (AKGEC), Ghaziabad",
         "Jaypee Institute of Information Technology (JIIT), Noida",
         "Aligarh Muslim University (AMU), Aligarh",
         "Dr. A.P.J. Abdul Kalam Technical University (AKTU), Lucknow","Other"],
         "Uttarakhand":[ "Indian Institute of Technology Roorkee (IIT Roorkee)",
         "National Institute of Technology Uttarakhand (NIT Uttarakhand), Srinagar",
         "Graphic Era University, Dehradun",
         "Dehradun Institute of Technology (DIT), Dehradun","Other"],
          "West Bengal":[ "Indian Institute of Technology Kharagpur (IIT Kharagpur)",
          "Indian Institute of Engineering Science and Technology Shibpur (IIEST Shibpur)",
          "Jadavpur University, Kolkata",
          "National Institute of Technology Durgapur (NIT Durgapur)",
          "University of Calcutta, Kolkata",
          "Bengal Engineering and Science University (BESU), Shibpur",
          "Kalyani Government Engineering College, Kalyani",
          "Haldia Institute of Technology, Haldia",
          "Heritage Institute of Technology, Kolkata",
          "Techno India University, Kolkata","Other"],
          "Arunachal Pradesh":["National Institute of Technology Arunachal Pradesh (NIT Arunachal Pradesh), Yupia",
          "North Eastern Regional Institute of Science and Technology (NERIST), Nirjuli",
          "Rajiv Gandhi Government Polytechnic, Itanagar",
          "Government Polytechnic, Dirang",
          "Donyi Polo Government College, Kamki",
          "Indira Gandhi Government College, Tezu",
          "Jawaharlal Nehru College, Pasighat",
          "Saint Claret College, Ziro",
          "Himalayan University, Itanagar",
          "Apex Professional University, Pasighat","Other"]
        
    }
   
form:FormGroup;


constructor(private fb:FormBuilder, private http:HttpClient,private userdetails:UserdetailsService,private route:Router){
    this.form=this.fb.group({
        // userid:['',Validators.required],
        last_name:['',Validators.required],
        username:['', Validators.required],
        gender:['', Validators.required],
        dob:['', Validators.required],
        email: ['', [Validators.required, Validators.email,Validators.pattern("^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$")]],
        password: ['', [Validators.required, Validators.minLength(8)]],
        // locations:['',Validators.required],
        // colleges:['', Validators.required],
        college_location:new FormControl(''),
        college_name:new FormControl(''),
        empskillids: []
    })


}
ngOnInit():void{
    this.getSkills()
}
toggleDropdownMenu(): void {
    this.showDropdownMenu = !this.showDropdownMenu;
  }
 
  
  toggleSkill(skill: string): void {
      this.userdetails.getSkillsId(skill).subscribe((res)=>{
          if (!this.empskillids.includes(res.id)) {
              this.empskillids.push(res.id);
              this.selectedSkills.push(res.skillName) // Add skill to selectedSkills array
            } else {
              this.empskillids = this.empskillids.filter(s => s !== res.id);
              this.selectedSkills = this.selectedSkills.filter(s => s !== res.skillName); // Remove skill from selectedSkills array
            }
            this.showDropdownMenu = false;
            
      })
      // Hide the dropdown after selecting/deselecting a skill
    }
   

 
  removeSkill(skill: string): void {
    this.selectedSkills = this.selectedSkills.filter(s => s !==skill);
    // Remove skill from selectedSkills array
    this.userdetails.getSkillsId(skill).subscribe((res)=>{
        this.empskillids = this.empskillids.filter(s => s !== res.id);
    })
 
  }
  getSkills():any[]{
    this.userdetails.getSkills().subscribe((res)=>{
      this.skills=res
    })
    console.log(this.skills)
    return this.skills;
  }

getColleges(){
    const selectedloc=this.form.get('college_location')?.value;
    return selectedloc ? this.colleges[selectedloc] || [] :[];
}
get formControls() {
    return this.form.controls;
  }
  get emailControl() {
    return this.form.get('email');
  }
submitForm() {
    const formDetails=JSON.parse(JSON.stringify(this.form.value))
    formDetails.empskillids = this.empskillids;
    
       if(this.form.valid)
        {
            this.userdetails.storeuserData(formDetails).subscribe((res)=>{
                console.log(res)
                alert("Registration Successful, Request is Sent")
            })
            console.log(formDetails)
            this.route.navigateByUrl('/login')
        
        }
        }
      
    //   updateSelectedRole(role: string): void {
    //     this.selectedRole = role;
    //     this.r.push(role);
    //   } 
    
}